language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsndfile1-dev libfftw3-dev liblapack3gf libblas3gf

install: ./travis_deps.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
